### ISSUE TITLE
Can't generate a config file 

### ISSUE THREAD

**Issue by seperatis** [CryptoGraphics/lyclMiner#16]
Windows 10 Pro
Radeon RX 580 GPU's
AMD Adrenaline 18.2.1

So I orginally tried this with Vertcoins One Click Miner, which utilizes your software. After it failed to create a config file, I un-installed it, then installed your "lycelMiner" instead. In both cases, I cannot see to generate a config file no matter what....

For some reason I can't get this to generate a config file. (lyclMiner.conf) When I run the GenerateConfig.bat with `lyclMiner -g lyclMiner.conf` it never produces a config file.....

Any idea what is going on here?

Here is the debug contents from Vertcoin One-Click miner: 

- 2018-10-01T07:50:46.9854344Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:50:47.0635725Z, LoadSettingsJSON: LoadSettings: OK.
- 2018-10-01T07:50:47.1104070Z, Form1_Load: Loaded: OK, V:1.2.0.0
- 2018-10-01T07:51:47.1679283Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:51:56.7767472Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:01.1959177Z, Download_Miner: Download Started
- 2018-10-01T07:52:08.5271926Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2018-10-01T07:52:08.5271926Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:12.2193060Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:29.8672327Z, Update_Miner_Config: System.IO.FileNotFoundException: Could not find file 'C:\Users\seper\Documents\Vertcoin One-Click Miner\amd\lyclminer\lyclMiner.conf'.
File name: 'C:\Users\seper\Documents\Vertcoin One-Click Miner\amd\lyclminer\lyclMiner.conf'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at VertcoinOneClickMiner.Main.Update_Miner_Config()
- 2018-10-01T07:52:29.8672327Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:29.8672327Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2018-10-01T07:52:29.9765864Z, Start_Miner: Start_Miner: OK.
- 2018-10-01T07:52:38.3248262Z, settings_Load: Loaded: OK.
- 2018-10-01T07:52:41.5527244Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:41.5527244Z, Button1_Click: Main() SaveSettings: OK.
- 2018-10-01T07:52:46.7023890Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:46.7023890Z, Settings_Closing: Closed: OK.
- 2018-10-01T07:52:47.7692896Z, Main_Closing: 

- 2018-10-01T07:52:47.7692896Z, Main_Closing: Closing: OK
- 2018-10-01T07:52:47.7692896Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:47.7849396Z, Kill_Miner: System.ArgumentException: Process with an Id of 6960 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at System.Diagnostics.Process.GetProcessById(Int32 processId)
   at VertcoinOneClickMiner.Main.Kill_Miner()
- 2018-10-01T07:52:47.7849396Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-10-01T07:52:47.7849396Z, Kill_Miner: Kill_Miner: OK.
- 2018-10-01T07:52:47.8005337Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-10-01T07:52:47.8005337Z, Main_Closing:

**Comment by CryptoGraphics** [comment]
This is related to Vertcoin One Click Miner and not lyclMiner.
